# Overview
More commonly than not, datasets we work with will contain null/ NA values. Null/ NA values represent the non-existence of information. That is, no value exists to interpret for a given datapoint. Nulls values can lead to miscalculations and some functions or models to error out. For example, some algorithms live support vector machines (SVMs) are infamous for nulls creating model bias.

Start with creating a dataframe...

In [0]:
from pyspark.sql.types import *

data=[(1001,'Chicago',535, None),            
      (1002,'Boston' ,495, None),            
      (1003,'Seattle',318, None ),
      (1004,'Columbia',None, None), 
      (1005,'Wilmington',311, None), 
      (1006,'Lancaster',None, None), 
      (1007,'Philidelphia',498,None),
      (None,None,None,None),
      ]

schema = StructType([
   StructField("station_id", IntegerType(), True),
   StructField("city"      , StringType() , True),
   StructField("rainfall"  , IntegerType(), True),
   StructField("comments"  , StringType() , True)])

sdf = spark.createDataFrame(data, 
                            schema) 

# Print top 5 rows
display(sdf)

station_id,city,rainfall,comments
1001,Chicago,535,null
1002,Boston,495,null
1003,Seattle,318,null
1004,Columbia,null,null
1005,Wilmington,311,null
1006,Lancaster,null,null
1007,Philidelphia,498,null
null,null,null,null

# Dealing with Null Values

### Drop any records with null:

The .na.drop() function will drop any rows with a null column. Because all of the rows have a null column, "comments", no records will be returned.

In [0]:
display(sdf.na.drop())       # returns no columns becuase all columns have null comments field
display(sdf.na.drop('any'))  # Another way to do

### Drop any records where all values are null:

Using the 'all' parameter within the drop function specifies the .na.drop() function to drop only rows with all fields null.

In [0]:
display(sdf.na.drop('all'))

station_id,city,rainfall,comments
1001,Chicago,535,null
1002,Boston,495,null
1003,Seattle,318,null
1004,Columbia,null,null
1005,Wilmington,311,null
1006,Lancaster,null,null
1007,Philidelphia,498,null

### Drop rows based on nulls within specified columns:

Dropping rows based on specific null values can be performed by nesting a subset() statement within the .na.drop() function.

In [0]:
# this can be done by specifying an individual column 
display(sdf.na.drop(subset=['rainfall'])) 

# or a list of columns (nothing displayed because comments is null for all records)
display(sdf.na.drop(subset=['rainfall','comments']))

station_id,city,rainfall,comments
1001,Chicago,535,null
1002,Boston,495,null
1003,Seattle,318,null
1005,Wilmington,311,null
1007,Philidelphia,498,null

### Replace Null Values

The .fill() function can be used in place of the .drop() function to replace NA's with specific values.

In [0]:
display(sdf.na.fill('empty'))

station_id,city,rainfall,comments
1001,Chicago,535,empty
1002,Boston,495,empty
1003,Seattle,318,empty
1004,Columbia,null,empty
1005,Wilmington,311,empty
1006,Lancaster,null,empty
1007,Philidelphia,498,empty
null,empty,null,empty

Only comments and city had nulls replaced becuase station_id and ranfill are integers whereas a string was placed within the .fill() function. <br>
Dictionaries can be can be input for column based null treatment.

In [0]:
null_mapping = {'station_id':9999, 'City':'Unknown', 'Rainfall':0, 'comments':'empty'}

display(sdf.na.fill(null_mapping))

station_id,city,rainfall,comments
1001,Chicago,535,empty
1002,Boston,495,empty
1003,Seattle,318,empty
1004,Columbia,0,empty
1005,Wilmington,311,empty
1006,Lancaster,0,empty
1007,Philidelphia,498,empty
9999,Unknown,0,empty